export class Constants{
    static DB_CONNECTION:string = 'DB_CONNECTION';
    static APP_CONFIGURATION_PROPERTIES:string = 'APP_CONFIGURATION_PROPERTIES';
    static APPLICATION_CONTEXT:string = 'APPLICATION_CONTEXT';
}