export enum OrderTypeEnum {
    TRANSFER_TO_CASH = 'TRANSFER_TO_CASH',
    TRANSFER_TO_BANK = 'TRANSFER_TO_BANK',
    CARD_TO_CASH = 'CARD_TO_CASH',
    CARD_TO_BANK = 'CARD_TO_BANK',
    CASH_TO_CASH = 'CASH_TO_CASH',
    CASH_TO_BANK = 'CASH_TO_BANK'
}